import {
    ArticleEnum,
    LevelEnum,
    NounWordType,
    WordGrammarType,
    WordInfo,
} from './RepitorTypes'

type WordListType = { [key: number]: NounWordType }
export const WordList: WordListType = {
    1: {
        text: 'Milch',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DIE,
        level: LevelEnum.A1,
        translate: 'milk',
    },
    2: {
        text: 'Kaffee',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        level: LevelEnum.A1,
        translate: 'coffee',
    },
    3: {
        text: 'Tee',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        level: LevelEnum.A1,
        translate: 'tea',
    },
    4: {
        text: 'Wein',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        level: LevelEnum.A1,
        translate: 'wine',
    },
    5: {
        text: 'Brot',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DAS,
        level: LevelEnum.A1,
        translate: 'bread',
    },
    6: {
        text: 'Wasser',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DAS,
        level: LevelEnum.A1,
        translate: 'water',
    },
    7: {
        text: 'Bier',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DAS,
        level: LevelEnum.A1,
        translate: 'bear',
    },
    8: {
        text: 'Vater',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        level: LevelEnum.A1,
        translate: 'father',
    },
    9: {
        text: 'Mutter',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DIE,
        level: LevelEnum.A1,
        translate: 'mother',
    },
    10: {
        text: 'Schwester',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DIE,
        level: LevelEnum.A1,
        translate: 'sister',
    },
    11: {
        text: 'Bruder',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        level: LevelEnum.A1,
        translate: 'brother',
    },
    12: {
        text: 'Mann',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        level: LevelEnum.A1,
        translate: 'husband',
    },
    13: {
        text: 'Frau',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DIE,
        level: LevelEnum.A1,
        translate: 'wife',
    },
    14: {
        text: 'Sohn',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        level: LevelEnum.A1,
        translate: 'son',
    },
    15: {
        text: 'Tochter',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DIE,
        level: LevelEnum.A1,
        translate: 'daughter',
    },
    16: {
        text: 'Junge',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DAS,
        level: LevelEnum.A1,
        translate: 'boy',
    },
    17: {
        text: 'Hund',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        level: LevelEnum.A1,
        translate: 'dog',
    },
    18: {
        text: 'Elefant',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        level: LevelEnum.A1,
        translate: 'elefant',
    },
    19: {
        text: 'Katze',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DIE,
        level: LevelEnum.A1,
        translate: 'cat',
    },
    20: {
        text: 'Maus',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DIE,
        level: LevelEnum.A1,
        translate: 'mause',
    },
    21: {
        text: 'Eule',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DIE,
        level: LevelEnum.A1,
        translate: 'owl',
    },
    22: {
        text: 'Bär',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        level: LevelEnum.A1,
        translate: 'bear',
    },
    23: {
        text: 'Käse',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        level: LevelEnum.A1,
        translate: 'cheese',
    },
    24: {
        text: 'Salat',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        level: LevelEnum.A1,
        translate: 'salat',
    },
}
