import {
    ArticleEnum,
    LevelEnum,
    NounWordType,
    WordGrammarType,
    WordInfo,
} from './RepitorTypes'

type WordListType = NounWordType[]

export const WordList: WordListType = [
    {
        text: 'Uhr',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DIE,
        translate: 'Clock',
    },
    {
        text: 'Ende',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DAS,
        translate: 'End',
    },
    {
        text: 'Zeit',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DIE,
        translate: 'Time',
    },
    {
        text: 'Stadt',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DIE,
        translate: 'City',
    },
    {
        text: 'Frau',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DIE,
        translate: 'Woman',
    },
    {
        text: 'Mann',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        translate: 'Man',
    },
    {
        text: 'Leben',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DAS,
        translate: 'Life',
    },
    {
        text: 'Welt',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DIE,
        translate: 'World',
    },
    {
        text: 'Land',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DAS,
        translate: 'country',
    },
    {
        text: 'Teil',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        translate: 'Part',
    },
    {
        text: 'Polizei',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DIE,
        translate: 'police',
    },
    {
        text: 'Geld',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DAS,
        translate: 'Money',
    },
    {
        text: 'Arbeit',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DIE,
        translate: 'Work',
    },
    {
        text: 'Platz',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        translate: 'Place',
    },
    {
        text: 'Anfang',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        translate: 'Beginning',
    },
    {
        text: 'Haus',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DAS,
        translate: 'House',
    },
    {
        text: 'Hilfe',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DIE,
        translate: 'Help',
    },
    {
        text: 'Leute',
        type: WordGrammarType.NOUN,
        alwaysPlural: true,
        article: ArticleEnum.DIE,
        translate: 'People',
    },
    {
        text: 'Ergebnis',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DAS,
        translate: 'Result',
    },
    {
        text: 'Gruppe',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DIE,
        translate: 'group',
    },
    {
        text: 'Beispiel',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DAS,
        translate: 'Example',
    },
    {
        text: 'Familie',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DIE,
        translate: 'Family',
    },
    {
        text: 'Bild',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DAS,
        translate: 'Picture',
    },
    {
        text: 'Hand',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DIE,
        translate: 'hand',
    },
    {
        text: 'Film',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        translate: 'Movie',
    },
    {
        text: 'Mitte',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DIE,
        translate: 'center',
    },
    {
        text: 'Buch',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DAS,
        translate: 'Book',
    },
    {
        text: 'Problem',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DAS,
        translate: 'problem',
    },
    {
        text: 'Eltern',
        type: WordGrammarType.NOUN,
        alwaysPlural: true,
        article: ArticleEnum.DIE,
        translate: 'Parents',
    },
    {
        text: 'Firma',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DIE,
        translate: 'company',
    },
    {
        text: 'Wasser',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DAS,
        translate: 'Water',
    },
    {
        text: 'Straße',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DIE,
        translate: 'Street',
    },
    {
        text: 'Mutter',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DIE,
        translate: 'Mother',
    },
    {
        text: 'Vater',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        translate: 'Father',
    },
    {
        text: 'Wort',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DAS,
        translate: 'Word',
    },
    {
        text: 'Kopf',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        translate: 'Head',
    },
    {
        text: 'Preis',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        translate: 'Price',
    },
    {
        text: 'Blick',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        translate: 'View',
    },
    {
        text: 'Stelle',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DIE,
        translate: 'Job',
    },
    {
        text: 'Internet',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DAS,
        translate: 'Internet',
    },
    {
        text: 'Raum',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        translate: 'Space',
    },
    {
        text: 'Angebot',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DAS,
        translate: 'Offer',
    },
    {
        text: 'Schule',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DIE,
        translate: 'School',
    },
    {
        text: 'Sprache',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DIE,
        translate: 'Language',
    },
    {
        text: 'Aufgabe',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DIE,
        translate: 'Task',
    },
    {
        text: 'Chef',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        translate: 'boss',
    },
    {
        text: 'Auto',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DAS,
        translate: 'automobile',
    },
    {
        text: 'Sohn',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        translate: 'Son',
    },
    {
        text: 'Ort',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        translate: 'Location',
    },
    {
        text: 'Kind',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DAS,
        translate: 'child',
    },
    {
        text: 'Verein',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        translate: 'Association',
    },
    {
        text: 'Mensch',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        translate: 'Person',
    },
    {
        text: 'Bank',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DIE,
        translate: 'Bank',
    },
    {
        text: 'Ausland',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DAS,
        translate: 'Abroad',
    },
    {
        text: 'Herr',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        translate: 'Mister',
    },
    {
        text: 'Tochter',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DIE,
        translate: 'Daughter',
    },
    {
        text: 'Stunde',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DIE,
        translate: 'Hour',
    },
    {
        text: 'Zeitung',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DIE,
        translate: 'Newspaper',
    },
    {
        text: 'Partner',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        translate: 'partner',
    },
    {
        text: 'Alter',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DAS,
        translate: 'Old',
    },
    {
        text: 'Wohnung',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DIE,
        translate: 'Apartment',
    },
    {
        text: 'Fehler',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        translate: 'Mistake',
    },
    {
        text: 'Computer',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        translate: 'computer',
    },
    {
        text: 'Kurs',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        translate: 'course',
    },
    {
        text: 'Antwort',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DIE,
        translate: 'Answer',
    },
    {
        text: 'Licht',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DAS,
        translate: 'Light',
    },
    {
        text: 'Satz',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        translate: 'Sentence',
    },
    {
        text: 'Heimat',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DIE,
        translate: 'Hometown',
    },
    {
        text: 'Papier',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DAS,
        translate: 'Paper',
    },
    {
        text: 'Jugendliche',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        translate: 'teenagers',
    },
    {
        text: 'Freund',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        translate: 'Friend',
    },
    {
        text: 'Text',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        translate: 'text',
    },
    {
        text: 'Tisch',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        translate: 'Table',
    },
    {
        text: 'Bahn',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DIE,
        translate: 'Train',
    },
    {
        text: 'Name',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        translate: 'Surname',
    },
    {
        text: 'Lehrer',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        translate: 'Teacher',
    },
    {
        text: 'Nummer',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DIE,
        translate: 'number',
    },
    {
        text: 'Moment',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        translate: 'moment',
    },
    {
        text: 'Sport',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        translate: 'Sports',
    },
    {
        text: 'Klasse',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DIE,
        translate: 'Class',
    },
    {
        text: 'Plan',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        translate: 'plan',
    },
    {
        text: 'Ordnung',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DIE,
        translate: 'Order',
    },
    {
        text: 'Hotel',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DAS,
        translate: 'hotel',
    },
    {
        text: 'Geburtstag',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        translate: 'Birthday',
    },
    {
        text: 'Praxis',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DIE,
        translate: 'Practice',
    },
    {
        text: 'Halle',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DIE,
        translate: 'Hall',
    },
    {
        text: 'Essen',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DAS,
        translate: 'Eat',
    },
    {
        text: 'Auskunft',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DIE,
        translate: 'Information',
    },
    {
        text: 'Rechnung',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DIE,
        translate: 'The invoice',
    },
    {
        text: 'Telefon',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DAS,
        translate: 'phone',
    },
    {
        text: 'Brief',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        translate: 'letter',
    },
    {
        text: 'Fahrer',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        translate: 'driver',
    },
    {
        text: 'Flughafen',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        translate: 'Airport',
    },
    {
        text: 'Feuer',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DAS,
        translate: 'Fire',
    },
    {
        text: 'Auge',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DAS,
        translate: 'Eye',
    },
    {
        text: 'Aussage',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DIE,
        translate: 'Statement',
    },
    {
        text: 'Arzt',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        translate: 'Physician',
    },
    {
        text: 'Fußball',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        translate: 'football',
    },
    {
        text: 'Dorf',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DAS,
        translate: 'Village',
    },
    {
        text: 'Post',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DIE,
        translate: 'post',
    },
    {
        text: 'Bruder',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        translate: 'Brother',
    },
    {
        text: 'Information',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DIE,
        translate: 'information',
    },
    {
        text: 'Kino',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DAS,
        translate: 'movie theater',
    },
    {
        text: 'Zug',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        translate: 'Train',
    },
    {
        text: 'Job',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        translate: 'job',
    },
    {
        text: 'Beruf',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        translate: 'Profession',
    },
    {
        text: 'Beamte',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        translate: 'Officer',
    },
    {
        text: 'Urlaub',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        translate: 'Vacation',
    },
    {
        text: 'Junge',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        translate: 'Boy',
    },
    {
        text: 'Arbeitsplatz',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        translate: 'Workplace',
    },
    {
        text: 'Wind',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        translate: 'wind',
    },
    {
        text: 'Zimmer',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DAS,
        translate: 'Room',
    },
    {
        text: 'Kasse',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DIE,
        translate: 'Checkout',
    },
    {
        text: 'Termin',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        translate: 'meeting',
    },
    {
        text: 'Ecke',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DIE,
        translate: 'Corner',
    },
    {
        text: 'Gast',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        translate: 'Guest',
    },
    {
        text: 'Studium',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DAS,
        translate: 'Studies',
    },
    {
        text: 'Meer',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DAS,
        translate: 'sea',
    },
    {
        text: 'Bier',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DAS,
        translate: 'Beer',
    },
    {
        text: 'Farbe',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DIE,
        translate: 'Color',
    },
    {
        text: 'Pause',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DIE,
        translate: 'Break',
    },
    {
        text: 'Gewicht',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DAS,
        translate: 'Weight',
    },
    {
        text: 'Kunde',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        translate: 'customer',
    },
    {
        text: 'Wetter',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DAS,
        translate: 'Weather',
    },
    {
        text: 'Maschine',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DIE,
        translate: 'machine',
    },
    {
        text: 'Bahnhof',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        translate: 'Railroad station',
    },
    {
        text: 'Bus',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        translate: 'bus',
    },
    {
        text: 'Regen',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        translate: 'Rain',
    },
    {
        text: 'Kollege',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        translate: 'Colleague',
    },
    {
        text: 'Schwester',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DIE,
        translate: 'Sister',
    },
    {
        text: 'See',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        translate: 'lake',
    },
    {
        text: 'Anzeige',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DIE,
        translate: 'Advertisement',
    },
    {
        text: 'Foto',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DAS,
        translate: 'photo',
    },
    {
        text: 'Foto',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DIE,
        translate: 'photo',
    },
    {
        text: 'Dank',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        translate: 'Thanks to',
    },
    {
        text: 'Mund',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        translate: 'mouth',
    },
    {
        text: 'Autobahn',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DIE,
        translate: 'Highway',
    },
    {
        text: 'Garten',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        translate: 'Garden',
    },
    {
        text: 'Glas',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DAS,
        translate: 'Glass',
    },
    {
        text: 'Bett',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DAS,
        translate: 'Bed',
    },
    {
        text: 'Eintritt',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        translate: 'entry',
    },
    {
        text: 'Dame',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DIE,
        translate: 'lady',
    },
    {
        text: 'Konto',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DAS,
        translate: 'Account',
    },
    {
        text: 'Restaurant',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DAS,
        translate: 'restaurant',
    },
    {
        text: 'Kaffee',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        translate: 'Coffee',
    },
    {
        text: 'Fleisch',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DAS,
        translate: 'Meat',
    },
    {
        text: 'Eingang',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        translate: 'Entrance',
    },
    {
        text: 'Flugzeug',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DAS,
        translate: 'Airplane',
    },
    {
        text: 'Stock',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        translate: 'floor',
    },
    {
        text: 'Tasche',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DIE,
        translate: 'Bag',
    },
    {
        text: 'Hund',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        translate: 'Dog',
    },
    {
        text: 'Adresse',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DIE,
        translate: 'address',
    },
    {
        text: 'Ehefrau',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DIE,
        translate: 'Wife',
    },
    {
        text: 'Datum',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DAS,
        translate: 'Date',
    },
    {
        text: 'Arm',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        translate: 'poor',
    },
    {
        text: 'Karte',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DIE,
        translate: 'Map',
    },
    {
        text: 'Baum',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        translate: 'Tree',
    },
    {
        text: 'Unterricht',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        translate: 'Instruction',
    },
    {
        text: 'Einladung',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DIE,
        translate: 'Invitation',
    },
    {
        text: 'Laden',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        translate: 'Load',
    },
    {
        text: 'Bitte',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DIE,
        translate: 'Please',
    },
    {
        text: 'Ausgang',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        translate: 'Exit',
    },
    {
        text: 'Wein',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        translate: 'Wine',
    },
    {
        text: 'Erwachsene',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        translate: 'Adult',
    },
    {
        text: 'Test',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        translate: 'test',
    },
    {
        text: 'Kindergarten',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        translate: 'kindergarten',
    },
    {
        text: 'Lied',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DAS,
        translate: 'song',
    },
    {
        text: 'Ehemann',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        translate: 'Husband',
    },
    {
        text: 'Haar',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DAS,
        translate: 'hair',
    },
    {
        text: 'Fax',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DAS,
        translate: 'fax',
    },
    {
        text: 'Freizeit',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DIE,
        translate: 'Leisure time',
    },
    {
        text: 'Kleidung',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DIE,
        translate: 'Clothing',
    },
    {
        text: 'CD',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DIE,
        translate: 'CD',
    },
    {
        text: 'Brot',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DAS,
        translate: 'Bread',
    },
    {
        text: 'Miete',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DIE,
        translate: 'Rent',
    },
    {
        text: 'Bauch',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        translate: 'Belly',
    },
    {
        text: 'Vorsicht',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DIE,
        translate: 'Caution',
    },
    {
        text: 'Milch',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DIE,
        translate: 'milk',
    },
    {
        text: 'Ankunft',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DIE,
        translate: 'Arrival',
    },
    {
        text: 'Bad',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DAS,
        translate: 'bath',
    },
    {
        text: 'Bein',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DAS,
        translate: 'leg',
    },
    {
        text: 'Student',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        translate: 'University student',
    },
    {
        text: 'Fahrrad',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DAS,
        translate: 'Bicycle',
    },
    {
        text: 'Hunger',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        translate: 'hunger',
    },
    {
        text: 'Fisch',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        translate: 'Fish',
    },
    {
        text: 'Party',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DIE,
        translate: 'party',
    },
    {
        text: 'Hochzeit',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DIE,
        translate: 'Wedding',
    },
    {
        text: 'S-Bahn',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DIE,
        translate: 'Train',
    },
    {
        text: 'Vermieter',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        translate: 'Landlord',
    },
    {
        text: 'Baby',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DAS,
        translate: 'infant',
    },
    {
        text: 'Unterschrift',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DIE,
        translate: 'Signature',
    },
    {
        text: 'Geschenk',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DAS,
        translate: 'Gift',
    },
    {
        text: 'Bogen',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        translate: 'arc',
    },
    {
        text: 'Handy',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DAS,
        translate: 'mobile',
    },
    {
        text: 'Schild',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DAS,
        translate: 'Sign',
    },
    {
        text: 'Flasche',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DIE,
        translate: 'Bottle',
    },
    {
        text: 'Koffer',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        translate: 'Suitcase',
    },
    {
        text: 'Kuchen',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        translate: 'Cake',
    },
    {
        text: 'Lokal',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DAS,
        translate: 'Local',
    },
    {
        text: 'Formular',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DAS,
        translate: 'Form',
    },
    {
        text: 'Abfahrt',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DIE,
        translate: 'Departure',
    },
    {
        text: 'Tee',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        translate: 'tea',
    },
    {
        text: 'Doktor',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        translate: 'doctor',
    },
    {
        text: 'Treppe',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DIE,
        translate: 'Stairs',
    },
    {
        text: 'Ausflug',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        translate: 'Side trip',
    },
    {
        text: 'Obst',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DAS,
        translate: 'Fruit',
    },
    {
        text: 'Großvater',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        translate: 'grandfather',
    },
    {
        text: 'Reparatur',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DIE,
        translate: 'repair',
    },
    {
        text: 'Großmutter',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DIE,
        translate: 'grandmother',
    },
    {
        text: 'Reis',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        translate: 'rice',
    },
    {
        text: 'Anruf',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        translate: 'Call',
    },
    {
        text: 'Entschuldigung',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DIE,
        translate: 'Excuse me',
    },
    {
        text: 'Ei',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DAS,
        translate: 'egg',
    },
    {
        text: 'Schluss',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        translate: 'Ending',
    },
    {
        text: 'Drucker',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        translate: 'Printer',
    },
    {
        text: 'Salz',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DAS,
        translate: 'Salt',
    },
    {
        text: 'Straßenbahn',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DIE,
        translate: 'tram',
    },
    {
        text: 'Bekannte',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        translate: 'Acquaintance',
    },
    {
        text: 'Zigarette',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DIE,
        translate: 'Cigarette',
    },
    {
        text: 'Zoll',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        translate: 'Customs',
    },
    {
        text: 'Wiedersehen',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DAS,
        translate: 'Goodbye',
    },
    {
        text: 'Wiederhören',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DAS,
        translate: 'Listen again',
    },
    {
        text: 'Vorwahl',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DIE,
        translate: 'Phone prefix',
    },
    {
        text: 'Vorname',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        translate: 'First name',
    },
    {
        text: 'Verwandte',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        translate: 'Related',
    },
    {
        text: 'Verkäufer',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        translate: 'Salesperson',
    },
    {
        text: 'Tomate',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DIE,
        translate: 'tomato',
    },
    {
        text: 'Toilette',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DIE,
        translate: 'Toilet',
    },
    {
        text: 'Ticket',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DAS,
        translate: 'ticket',
    },
    {
        text: 'Taxi',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DAS,
        translate: 'taxi',
    },
    {
        text: 'Speisekarte',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DIE,
        translate: 'Menu',
    },
    {
        text: 'Sofa',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DAS,
        translate: 'sofa',
    },
    {
        text: 'Sehenswürdigkeit',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DIE,
        translate: 'Sightseeing',
    },
    {
        text: 'Schwimmbad',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DAS,
        translate: 'Swimming pool',
    },
    {
        text: 'Schüler',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        translate: 'Pupils',
    },
    {
        text: 'Schuh',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        translate: 'shoe',
    },
    {
        text: 'Schrank',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        translate: 'Wardrobe',
    },
    {
        text: 'Schlüssel',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        translate: 'Key',
    },
    {
        text: 'Schinken',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        translate: 'Ham',
    },
    {
        text: 'Schalter',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        translate: 'Switch',
    },
    {
        text: 'Salat',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        translate: 'salad',
    },
    {
        text: 'Saft',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        translate: 'Juice',
    },
    {
        text: 'Rezeption',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DIE,
        translate: 'reception',
    },
    {
        text: 'Reisebüro',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DAS,
        translate: 'Travel agency',
    },
    {
        text: 'Prüfung',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DIE,
        translate: 'Test',
    },
    {
        text: 'Prospekt',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        translate: 'brochure',
    },
    {
        text: 'Praktikum',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DAS,
        translate: 'Internship',
    },
    {
        text: 'Postleitzahl',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DIE,
        translate: 'Postal code',
    },
    {
        text: 'Pommes',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DIE,
        translate: 'French fries',
    },
    {
        text: 'Pass',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        translate: 'passport',
    },
    {
        text: 'Opa',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        translate: 'Grandpa',
    },
    {
        text: 'Oma',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DIE,
        translate: 'granny',
    },
    {
        text: 'Möbel',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DIE,
        translate: 'Furniture',
    },
    {
        text: 'Mädchen',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DAS,
        translate: 'Girl',
    },
    {
        text: 'Lösung',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DIE,
        translate: 'Solution',
    },
    {
        text: 'Lastkraftwagen',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        translate: 'Trucks',
    },
    {
        text: 'Kühlschrank',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        translate: 'Refrigerator',
    },
    {
        text: 'Kugelschreiber',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        translate: 'Ballpoint pen',
    },
    {
        text: 'Küche',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DIE,
        translate: 'Kitchen',
    },
    {
        text: 'Kiosk',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        translate: 'kiosk',
    },
    {
        text: 'Kartoffel',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DIE,
        translate: 'Potato',
    },
    {
        text: 'Jacke',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DIE,
        translate: 'Jacket',
    },
    {
        text: 'Hobby',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DAS,
        translate: 'hobby',
    },
    {
        text: 'Herd',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        translate: 'stove',
    },
    {
        text: 'Hausmann',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        translate: 'Hausmann',
    },
    {
        text: 'Hausfrau',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        translate: 'housewife',
    },
    {
        text: 'Hausaufgabe',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DIE,
        translate: 'Homework',
    },
    {
        text: 'Haltestelle',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DIE,
        translate: 'bus stop',
    },
    {
        text: 'Halbpension',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DIE,
        translate: 'Half board',
    },
    {
        text: 'Hähnchen',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DAS,
        translate: 'Chicken',
    },
    {
        text: 'Gruß',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        translate: 'greeting',
    },
    {
        text: 'Großeltern',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DIE,
        translate: 'grandparents',
    },
    {
        text: 'Größe',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DIE,
        translate: 'Size',
    },
    {
        text: 'Glückwunsch',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        translate: 'Congratulations',
    },
    {
        text: 'Glück',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DAS,
        translate: 'Happiness',
    },
    {
        text: 'Gleis',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DAS,
        translate: 'Track',
    },
    {
        text: 'Getränk',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DAS,
        translate: 'Drink',
    },
    {
        text: 'Gespräch',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DAS,
        translate: 'Conversation',
    },
    {
        text: 'Geschwister',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DIE,
        translate: 'Siblings',
    },
    {
        text: 'Geschäft',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DAS,
        translate: 'Business',
    },
    {
        text: 'Gepäck',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DAS,
        translate: 'Baggage',
    },
    {
        text: 'Gemüse',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DAS,
        translate: 'Vegetables',
    },
    {
        text: 'Geburtsort',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        translate: 'Place of birth',
    },
    {
        text: 'Geburtsjahr',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DAS,
        translate: 'Year of birth',
    },
    {
        text: 'Führung',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DIE,
        translate: 'Guide',
    },
    {
        text: 'Frühstück',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DAS,
        translate: 'Breakfast',
    },
    {
        text: 'Abflug',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        translate: 'departure',
    },
    {
        text: 'Fieber',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DAS,
        translate: 'Fever',
    },
    {
        text: 'Familienstand',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        translate: 'Marital status',
    },
    {
        text: 'Familienname',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        translate: 'family name',
    },
    {
        text: 'Fahrkarte',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DIE,
        translate: 'ticket',
    },
    {
        text: 'Empfänger',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        translate: 'Recipient',
    },
    {
        text: 'E-Mail',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DIE,
        translate: 'e-mail',
    },
    {
        text: 'Einzelzimmer',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DAS,
        translate: 'Single room',
    },
    {
        text: 'Durst',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        translate: 'thirst',
    },
    {
        text: 'Durchsage',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DIE,
        translate: 'announcement',
    },
    {
        text: 'Doppelzimmer',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DAS,
        translate: 'Double room',
    },
    {
        text: 'Disco',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DIE,
        translate: 'Disco',
    },
    {
        text: 'Café',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DAS,
        translate: 'Coffee shop',
    },
    {
        text: 'Butter',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DIE,
        translate: 'butter',
    },
    {
        text: 'Buchstabe',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        translate: 'Letter',
    },
    {
        text: 'Brötchen',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DAS,
        translate: 'Bread roll',
    },
    {
        text: 'Briefmarke',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        translate: 'Stamp',
    },
    {
        text: 'Blume',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DIE,
        translate: 'flower',
    },
    {
        text: 'Bleistift',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        translate: 'Pencil',
    },
    {
        text: 'Birne',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DIE,
        translate: 'Pear',
    },
    {
        text: 'Banane',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DIE,
        translate: 'banana',
    },
    {
        text: 'Balkon',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        translate: 'balcony',
    },
    {
        text: 'Bahnsteig',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        translate: 'platform',
    },
    {
        text: 'Bäckerei',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DIE,
        translate: 'Bakery',
    },
    {
        text: 'Automat',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        translate: 'automat',
    },
    {
        text: 'Ausweis',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        translate: 'ID',
    },
    {
        text: 'Ausweis',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        translate: 'ID',
    },
    {
        text: 'Ausländer',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        translate: 'Foreigner',
    },
    {
        text: 'Aufzug',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        translate: 'Elevator',
    },
    {
        text: 'Appetit',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        translate: 'appetite',
    },
    {
        text: 'Apfel',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        translate: 'Apple',
    },
    {
        text: 'Apartment',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DAS,
        translate: 'Apartment',
    },
    {
        text: 'Anschluss',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        translate: 'Connection',
    },
    {
        text: 'Ansage',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DIE,
        translate: 'announcement',
    },
    {
        text: 'Absender',
        type: WordGrammarType.NOUN,
        article: ArticleEnum.DER,
        translate: 'Sender',
    },
]
